# Setup
title: 'Introduction to Data-Centric AI'
title_short: 'Introduction to Data-Centric AI'
url: https://dcai.csail.mit.edu

nav:
  - name: Lectures
    url: /lectures/
  - name: Labs
    url: https://github.com/dcai-course/dcai-lab
  - name: Resources
    url: /resources/

collections:
  lectures:
    output: true

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/New_York

analytics:
  tracking_id: "G-42TY6091V2"

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Dockerfile
  - docker-compose.yml
